version: '3'
services:
  gsa:
    container_name: gsa
    build:
      context: .
      args:
        PORT: 11238 # The server reports this port to the master server. (Default: 11235)
        USERNAME: Docker # Set your username.
        SOURCE: https://geneshiftauto.com/downloads/GeneShiftAuto1490.tar.gz # Optionally override Gene Shift Auto source url. (required until `-latest.tar.gz` is available)
        CONFIG: default-config.ini # Config to load from `configs` folder.
        WEAPONS: default-weapons.ini # Weapons file to apply to a server (only if APPLYWEAPONS is true)
        APPLYWEAPONS: "false" # Overwrite weapons.ini from `configs/WEAPONS` (default false)
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "11238:11238/udp" # Use the same host:container port combo for the master server.
