version: '3'
services:
  gsa:
    container_name: gsa
    build:
      context: .
      args:
        PORT: 11237 # The server reports this port to the master server. (Default: 11235)
        USERNAME: Docker # Set your username.
        SOURCE: https://geneshiftauto.com/downloads/GeneShiftAuto1490.tar.gz # Optionally override Gene Shift Auto source url.
        CONFIG: default.ini # Config to load from `configs` folder.
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "11237:11237" # Use the same host:container port combo for the master server.
    volumes:
      - ./GSA/:/home/GSA/
